apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservice-dev

resources:
  - ../../base

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: simple-web-app
    spec:
      replicas: 2
