apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-application-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: dev
        namespace: web-dev
        cluster: in-cluster
        path: overlays/dev
      - name: staging
        namespace: web-staging
        cluster: in-cluster
        path: overlays/staging
      - name: prod
        namespace: web-prod
        cluster: in-cluster
        path: overlays/prod
  template:
    metadata:
      name: 'web-app-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/BBrucelee2002/argocd-appset-demo.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{cluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true